<?php

namespace BusinessCore\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WebuserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebuserRepository extends EntityRepository
{
}
