<?php

namespace BusinessCore\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WebuserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebuserRepository extends EntityRepository {

    /**
     *
     * @param \BusinessCore\Entity\Repository\Business $business
     * @return Webuser
     */
    public function findWebUserByBusiness(Business $business) {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
                'SELECT w FROM \BusinessCore\Entity\Webuser w ' .
                'WHERE w.business = :business'
        );

        $query->setParameter('business', $business);

        return $query->getOneOrNullResult();
    }

}
